services:
  fetch-schedules:
    build: .
    container_name: fetch-schedules
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/var/log
    environment:
      - TZ=Europe/Paris

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask-app
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
    environment:
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sncf.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.sncf.loadbalancer.server.port=5000"
      - "traefik.http.routers.sncf.entrypoints=websecure"
      - "traefik.http.routers.sncf.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sncf.tls=true"
